#!/usr/bin/env python3
from subprocess import check_output, STDOUT, CalledProcessError
import argparse


class File:
    def __init__(self, filename, compiler):
        self.filename = filename
        self.compiler = compiler

    def errorsize(self) -> int:
        """Get the size of an error from compiling"""
        try:
            check_output([self.compiler, self.filename], stderr=STDOUT)
        except CalledProcessError as e:
            return len(e.output.decode("utf-8"))

    def filesize(self) -> int:
        """Get the filesize"""
        length = check_output(f"cat {self.filename}", shell=True)
        return len(length.decode("utf-8"))

    def ratio(self) -> int:
        return self.errorsize() / self.filesize()


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("-c", help="Compiler name")
    parser.add_argument("-f", help="File name")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    test = File(args.f, args.c)
    print("Score:", test.ratio())
